export { ReactComponent as Logo } from './logo.svg';
export { ReactComponent as FacebookIcon } from './facebook.svg';
export { ReactComponent as GoogleIcon } from './google.svg';
export { ReactComponent as GithubIcon } from './github.svg';
export { ReactComponent as Register } from './register.svg';
export { ReactComponent as ImageVector } from './vector-image.svg';
export { ReactComponent as GlobeIcon } from './icon-globe.svg';
export { ReactComponent as LockIcon } from './icon-lock.svg';
export { ReactComponent as AddListIcon } from './icon-add-list.svg';
